### PR TITLE
Curtains!

### LINKED ISSUE #35: Curtains
Need some black curtains that allow players to walkthrough them but does not allow any light passed. This is for the theater

### PR DESCRIPTION
**Pull request by itsbazke**
This is for https://github.com/LoveTropics/LTExtras/issues/35

Blocks light! You can walk through them! Fancy!

Texture could use some improvement, I'll see what I can do about that. But at least there is code! 

It is basically a retextured glass pane that blocks light and has no collision. The blockstates were a mess to write in code so I took inspiration from `Infertile Vine` and used some json from vanilla (I took it from 1.20.1.jar and changed it, can we do that?).

Screenshots and videos don't really do it justice, its not that dark. Second image is mspaint hand stitched textures so you have to use some imagination (its somewhere in between)!

Untitled

image

### CODE REVIEW

**Review by Gegy — APPROVED** [review]
This looks great to me - awesome work! 🎉

**Comment by itsbazke** [comment]
A friend of mine who is a muuuch better artist volunteered to draw something a bit nicer! Will hold on to this and see what he comes up with :)

**Comment by NotActuallyTerry** [comment]
@martinnilsson how are we with this?

**Comment by itsbazke** [comment]
> @martinnilsson how are we with this?

My friend still didn't have time to fix the textures, but we could merge it right now and just update them later?

**Comment by NotActuallyTerry** [comment]
Yeah I'm happy to merge now and update later. Then builders can get them in-world!

**Pull request merged**
